name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          requirements.txt

    - name: Install dependencies
      env:
        PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e . --prefer-binary
    - name: Run tests
      run: |
        pytest -vv -n auto
