---
name: Python Tests

# yamllint disable rule:truthy
on:
  push:
    branches: [main]
  pull_request:
# yamllint enable rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - name: Restore venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.11-${{ hashFiles('requirements.txt') }}

      - name: Ensure venv on PATH
        run: echo ".venv/bin" >> $GITHUB_PATH

      - name: Build venv if needed
        if: steps.restore-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate

      - name: Install project dependencies
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -vv -n auto

      - name: Save venv
        uses: actions/cache/save@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.11-${{ hashFiles('requirements.txt') }}
